import itertools
from utility import is_prime, up_to, primes

def eval_polynomial(coefficients, x):
    """Evaluates a polynomial at the given point.

    The polynomial is expressed as a sequence of coefficients.

    Example, evaluate x^2 + 2*x + 3 at x=4
    >>> eval_polynomial((1, 2, 3), 4)
    27
    """
    value = 0
    for e, c in enumerate(reversed(coefficients)):
        value += c * x**e
    return value

def prime_sequence_length(coefficients):
    """
    Find the length of the prime sequence generated by a polynomial.

    >>> prime_sequence_length((1, 1, 41))
    40
    >>> prime_sequence_length((1, -79, 1601))
    80
    """
    for n in itertools.count():
        if not is_prime(eval_polynomial(coefficients, n)):
            return n

MAX_NUM = 1000 - 1
max_poly = None
max_length = 0
for a in range(-MAX_NUM, MAX_NUM + 1):
    for b in up_to(MAX_NUM, primes()):
        poly = (1, a, b)
        l = prime_sequence_length(poly)
        if l > max_length:
            max_poly = poly
            max_length = l
_, max_a, max_b = max_poly
print(max_a * max_b)
